add selection menu

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,13 +1,34 @@
 #!/usr/bin/env bash
 
-#-- Banner -----------------------------------------------------------------------------------------
-clear
-printf '\e[1m'
-printf '          888          888     .d888 d8b 888                  \n'
-printf '          888          888    d88P"  Y8P 888                  \n'
-printf '          888          888    888        888                  \n'
-printf '      .d88888  .d88b.  888888 888888 888 888  .d88b.  .d8888b \n'
-printf '     d88" 888 d88""88b 888    888    888 888 d8P  Y8b 88K     \n'
-printf '     888  888 888  888 888    888    888 888 88888888 "Y8888b.\n'
-printf '     Y88b 888 Y88..88P Y88b.  888    888 888 Y8b.          X88\n'
-printf '      "Y88888  "Y88P"   "Y888 888    888 888  "Y8888   88888P" \e[0m\n\n'
+#-- Config -----------------------------------------------------------------------------------------
+DOTFILES_DIRECTORY="${HOME}/.dotfiles"
+DOTFILES_TAR_REPO="https://github.com/nulliel/dotfiles/tarball/master" # EDIT THIS WHEN FORKING
+
+#-- Check for preexisting configuration ----------------------------------------
+if [[ -d ${DOTFILES_DIRECTORY} ]]; then
+    printf "[\e[1;91mError\e[0m] An existing dotfiles configuration has been found\n"
+    exit 1
+fi
+
+#-- Download Dotfiles ------------------------------------------------------------------------------
+if [[ ! -d ${DOTFILES_DIRECTORY} ]]; then
+    printf "Downloading dotfiles..."
+    mkdir ${DOTFILES_DIRECTORY}
+
+    # Download the tarball
+    curl -fsSLo /tmp/dotfiles.tar.gz ${DOTFILES_TAR_REPO} || {
+        printf "\e[91mERROR\e[0m\n"
+        exit 1
+    }
+
+    # Extract the tarball
+    tar -zxf /tmp/dotfiles.tar.gz --strip-components 1 -C ${DOTFILES_DIRECTORY}
+
+    # Remove the tarball
+    rm -rf /tmp/dotfiles.tar.gz
+
+    printf "\e[92mOK\e[0m\n"
+fi
+
+#-- Install Dotfiles -------------------------------------------------------------------------------
+source $DOTFILES_DIRECTORY/bin/dotfiles --no-sync
