rename dotfiles directory variable

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,31 +1,34 @@
 #!/usr/bin/env bash
 
 #-- Config -----------------------------------------------------------------------------------------
-DOTFILES_DIRECTORY="${HOME}/.dotfiles"
-DOTFILES_TAR_PATH="https://github.com/nulliel/dotfiles/tarball/master"
+DOTFILES_DIR="${HOME}/.dotfiles"
+DOTFILES_TAR="https://github.com/nulliel/dotfiles/tarball/master"
 
-#-- Check for preexisting configuration ------------------------------------------------------------
-if [[ -d "${DOTFILES_DIRECTORY}" || -f "${DOTFILES_DIRECTORY}" ]]; then
-  printf "[\033[1;91mError\033[0m] An existing dotfiles configuration has been found\n";
+dotfiles_tar=$(mktemp)
+
+#-- Create dotfiles directory ----------------------------------------------------------------------
+if [[ -d "${DOTFILES_DIR}" || -f "${DOTFILES_DIR}" ]]; then
+  printf "[\033[1;91mError\033[0m] An existing dotfiles configuration has been found.\n";
   exit 1
 fi
 
-mkdir "${DOTFILES_DIRECTORY}" || {
-  printf "[\033[1;91mError\033[0m] Failed to create dotfiles directory\n";
+mkdir "${DOTFILES_DIR}" || {
+  printf "[\033[1;91mError\033[0m] Failed to create dotfiles directory.\n";
   exit 1
 }
 
 #-- Download dotfiles ------------------------------------------------------------------------------
 printf "Downloading dotfiles...\n"
 
-readonly dotfiles_tar_file=$(mktemp)
-
-curl -fsSLo "${dotfiles_tar_file}" "${DOTFILES_TAR_PATH}" || {
-  printf "[\033[1;91mError\033[0m]] Failed to download dotfiles tarball\n";
+curl -fsLo "$dotfiles_tar" "$DOTFILES_TAR" || {
+  printf "[\033[1;91mError\033[0m]] Failed to download dotfiles.\n";
   exit 1
 }
 
-tar -zxf "${dotfiles_tar_file}" --strip-components 1 -C "${DOTFILES_DIRECTORY}"
+#-- Extract dotfiles -------------------------------------------------------------------------------
+printf "Extracting dotfiles...\n"
+
+tar -zxf "$dotfiles_tar" --strip-components 1 -C "$DOTFILES_DIR"
 
 #-- Run dotfiles -----------------------------------------------------------------------------------
-source "${DOTFILES_DIRECTORY}/bin/dotfiles"
+source "${DOTFILES_DIR}/bin/dotfiles"
