add link defaults and confirmation

diff --git a/lib/links b/lib/links
--- a/lib/links
+++ b/lib/links
@@ -1,43 +1,58 @@
 #!/usr/bin/env bash
 
-u_header "link"
+header "link"
 
-function create_link() {
-  local link_from="${DOTFILES_DIRECTORY}/$1"
+#-- Check for flags --------------------------------------------------------------------------------
+if is_set "NO_LINKS"; then
+  skip "Creating links..."
+  exit_header && return
+fi
+
+#-- Confirm linking --------------------------------------------------------------------------------
+if ! confirm_default "Create symlinks?"; then
+  skip "Creating links..."
+  exit_header && return
+fi
+
+#-- Link function ----------------------------------------------------------------------------------
+link_home () {
+  local link_from="${DOTFILES_DIR}/$1"
   local link_to="${HOME}/$2"
 
-  u_print "Linking $link_to..."
+  log "Linking $link_to..."
 
   if [[ -f "$link_to" || -d "$link_to" ]]; then
     if [[ "$(readlink -f $link_to)" = "$link_from" ]]; then
-      u_skip
+      skip
       return
     fi
 
-    u_fail
-    u_error "File $link_to already exists and is not linked."
+    fail
+    die "File $link_to already exists and is not linked." 71
   fi
 
   ln -s "$link_from" "$link_to" || {
-    u_fail
-    exit 1
+    fail
+    die "Failed to create link $link_from->$link_to" 72
   }
-  u_pass
+
+  pass
 }
 
-create_link "shell/bash_aliases"   ".bash_aliases"
-create_link "shell/bash_exports"   ".bash_exports"
-create_link "shell/bash_functions" ".bash_functions"
-create_link "shell/bash_nocommit"  ".bash_nocommit"
-create_link "shell/bash_options"   ".bash_options"
-create_link "shell/bash_paths"     ".bash_paths"
-create_link "shell/bash_profile"   ".bash_profile"
-create_link "shell/bashrc"         ".bashrc"
-create_link "config/deadbeef"      ".config/deadbeef"
-create_link "config/mpv"           ".config/mpv"
-create_link "emacs.d"              ".emacs.d"
-create_link "git/gitconfig"        ".gitconfig"
-create_link "git/gitignore"        ".gitignore"
-create_link "config/npmrc"         ".npmrc"
+#-- Links ------------------------------------------------------------------------------------------
+link_home "shell/bash_aliases"   ".bash_aliases"
+link_home "shell/bash_exports"   ".bash_exports"
+link_home "shell/bash_functions" ".bash_functions"
+link_home "shell/bash_nocommit"  ".bash_nocommit"
+link_home "shell/bash_options"   ".bash_options"
+link_home "shell/bash_paths"     ".bash_paths"
+link_home "shell/bash_profile"   ".bash_profile"
+link_home "shell/bashrc"         ".bashrc"
+link_home "config/deadbeef"      ".config/deadbeef"
+link_home "config/mpv"           ".config/mpv"
+link_home "emacs.d"              ".emacs.d"
+link_home "git/gitconfig"        ".gitconfig"
+link_home "git/gitignore"        ".gitignore"
+link_home "config/npmrc"         ".npmrc"
 
-u_exit_header
+exit_header
