add mpv

diff --git a/lib/utils-build b/lib/utils-build
--- a/lib/utils-build
+++ b/lib/utils-build
@@ -55,7 +55,18 @@ _do_build_autogen () {
       pass
       ;;
     "waf")
+      log "Running ./bootstrap.py..."
 
+      if [[ ! -f "./bootstrap.py" ]]; then
+        skip && return
+      fi
+
+      show_progress ./bootstrap.py || {
+        fail
+        die "Build failed on ./bootstrap.py" 51
+      }
+
+      pass
       ;;
     *)
       error "Unknown build tool $1" && exit 1
@@ -85,7 +96,14 @@ _do_build_configure () {
       pass
       ;;
     "waf")
+      log "Running ./waf configure $@..."
 
+      show_progress ./waf configure "$@" || {
+        fail
+        die "Build failed on ./waf configure $@" 56
+      }
+
+      pass
       ;;
     *)
       error "Unknown build tool $1" && exit 1
@@ -107,7 +125,14 @@ _do_build_make () {
       pass
       ;;
     "waf")
+      log "Running ./waf build..."
 
+      show_progress ./waf build || {
+        fail
+        die "Build failed on ./waf build" 57
+      }
+
+      pass
       ;;
     *)
       error "Unknown build tool $1" && exit 1
@@ -129,7 +154,14 @@ _do_build_install () {
       pass
       ;;
     "waf")
+      log "Running ./waf install.."
 
+      show_progress sudo ./waf install || {
+        fail
+        die "Build failed on ./waf install" 54
+      }
+
+      pass
       ;;
     *)
       error "Unknown build tool $1" && exit 1
@@ -155,7 +187,23 @@ _do_build_cleanup () {
 
 #-- WAF build sytem --------------------------------------------------------------------------------
 do_waf_install () {
-  :
+  local source_url="$1"                                             # URL to download
+  local source_file="${DOTFILES_TMP}/$(random_string 16).tar.gz"    # File to download to
+  local source_folder="${DOTFILES_TMP}/$(random_string 16)"         # Folder to extract to
+
+  shift
+
+  _do_build_download "$source_url" "$source_file"
+  _do_build_extract "$source_file" "$source_folder"
+
+  cd "$source_folder"
+
+  _do_build_autogen "waf"
+  _do_build_configure "waf" "$@"
+  _do_build_make "waf"
+  _do_build_install "waf"
+
+  _do_build_cleanup "$source_file" "$source_folder"
 }
 
 #-- Make build system ------------------------------------------------------------------------------
