normalize codebase to use internal functions whenever possible

diff --git a/lib/internal/sync b/lib/internal/sync
--- a/lib/internal/sync
+++ b/lib/internal/sync
@@ -2,63 +2,57 @@
 
 #-- Check flags ------------------------------------------------------------------------------------
 if [[ "$NO_SYNC" = true ]]; then
-  printf "Syncing dotfiles...\033[1;93mSKIPPING\033[0m\n"
+  skip "Syncing dotfiles..."
   return
 fi
 
 #-- Initialize the git repository ------------------------------------------------------------------
-printf "Initializing git repository..."
+clogl "Initializing git repository..."
 
 if [[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" != "true" ]]; then
-  git init >/dev/null 2>&1 || {
-    printf "\033[1;91mERROR\033[0m\n"
-    printf "[\033[1;91mError\033[0m] Failed to initialize git repository\n"
-    exit 21
+  git init 1>&3 2>&4 || {
+    fail
+    fatal "Failed to initialize git repository"
   }
 
-  git remote add origin "${DOTFILES_GIT_REMOTE}" >/dev/null 2>&1 || {
-    printf "\033[1;91mERROR\033[0m\n"
-    printf "[\033[1;91mError\033[0m] Failed to add remote\n"
-    exit 22
+  git remote add origin "${DOTFILES_GIT_REMOTE}" 1>&3 2>&4 || {
+    fail
+    fatal "Failed to add remote"
   }
 
-  git fetch origin master >/dev/null 2>&1 || {
-    printf "\033[1;91mERROR\033[0m\n"
-    printf "[\033[1;91mError\033[0m] Failed to fetch origin\n"
-    exit 23
+  git fetch origin master 1>&3 2>&4 || {
+    fail
+    fatal "Failed to fetch origin"
   }
 
-  git reset --hard FETCH_HEAD >/dev/null 2>&1 || {
-    printf "\033[1;91mERROR\033[0m\n"
-    printf "[\033[1;91mError\033[0m] Failed to reset branch\n"
-    exit 24
+  git reset --hard FETCH_HEAD 1>&3 2>&4 || {
+    fail
+    fatal "Failed to reset branch"
   }
 
-  git clean -fd >/dev/null 2>&1
+  git clean -fd 1>&3 2>&4
 
-  printf "\033[1;92mOK\033[0m\n"
+  pass
 else
-  printf "\033[1;93mSKIPPING\033[0m\n"
+  skip
 fi
 
 #-- Sync the repository ----------------------------------------------------------------------------
-printf "Syncing dotfiles..."
+clogl "Syncing dotfiles..."
 
-git pull --rebase origin master >/dev/null 2>&1 || {
-  printf "\033[1;91mERROR\033[0m\n"
-  printf "[\033[1;91mError\033[0m] Failed to sync to remote repository\n"
-  exit 25
+git pull --rebase origin master 1>&3 2>&4 || {
+  fail
+  fatal "Failed to sync to remote repository"
 }
 
-printf "\033[1;92mOK\033[0m\n"
+pass
 
 #-- Update modules ---------------------------------------------------------------------------------
-printf "Updating submodules..."
+clogl "Updating submodules..."
 
-git submodule update --recursive --init >/dev/null 2>&1 || {
-  printf "\033[1;91mERROR\033[0m\n"
-  printf "[\033[1;91mError\033[0m] Failed to update submodules\n"
-  exit 26
+git submodule update --recursive --init 1>&3 2>&4 || {
+  fail
+  fatal "Failed to update submodules"
 }
 
-printf "\033[1;92mOK\033[0m\n"
+pass
