Arch Linux overhaul

diff --git a/lib/internal/utils-package b/lib/internal/utils-package
--- a/lib/internal/utils-package
+++ b/lib/internal/utils-package
@@ -1,28 +1,52 @@
 #!/usr/bin/env bash
 
-#-- Check for existing package ---------------------------------------------------------------------
-package_installed () {
-  pacman -Q "$1" >/dev/null 2>&1 \
-    || command_exists "$1" \
-    || return 1
-  return 0
-}
+#-- Definitions ---------------------------------------------------------------------
+packageInstall () {
+  local packageName="${1}"
+  local noconfirm=false
 
-#-- Package install --------------------------------------------------------------------------------
-package_install () {
-  log "Installing $1..."
-
-  if package_installed "$1"; then
-    skip && return
+  if [[ "${packageName:0:11}" == "--noconfirm" ]]; then
+    packageName="${2}"
+    noconfirm=true
   fi
 
-  show_progress sudo pacman -Syu --needed "$1" && pass || {
-    fail
-    fatal "Package ($1) failed to install"
-  }
+  trySubheader "${packageName}"
+
+  if _packageInstalled "${packageName}"; then
+    skip "Installing ${packageName}..."
+    tryExitSubheader "${packageName}"
+    return
+  fi
+
+  clog "Installing ${packageName}..."
+
+  if [[ "${noconfirm}" == true ]]; then
+    checkSuccess showProgress sudo pacman -Syu --needed --noconfirm "${packageName}" \
+      || fatal "Package (${packageName}) failed to install"
+  else
+    checkSuccess showProgress sudo pacman -Syu --needed "${packageName}" \
+      || fatal "Package (${packageName}) failed to install"
+  fi
+
+  tryExitSubheader "${packageName}"
 }
 
-#-- Build tools ------------------------------------------------------------------------------------
-install_build_tools () {
-  package_install "base-devel"
+packageInstallList () {
+  local title="${1}"; shift
+  trySubheader "${title}"
+
+  while [[ "${#}" -ne 0 ]]; do
+    packageInstall "${1}"
+    shift
+  done
+
+  tryExitSubheader "${title}"
+}
+
+#-- Utilities --------------------------------------------------------------------------------------
+_packageInstalled () {
+  pacman -Q "$1" >/dev/null 2>&1 \
+    || commandExists "$1" \
+    || return 1
+  return 0
 }
diff --git a/lib/links b/lib/links
--- a/lib/links
+++ b/lib/links
@@ -3,49 +3,43 @@
 header "link"
 
 #-- Link function ----------------------------------------------------------------------------------
-link_home () {
-  local link_from="${DOTFILES_DIR}/links/$1"
-  local link_to="${HOME}/$2"
-  local link_path="$(readlink -f $link_to)"
+linkHome () {
+  local linkFrom="${DOTFILES_DIR}/links/$1"
+  local linkTo="${HOME}/$2"
+  local linkPath="$(readlink -f ${linkTo})"
 
-  log "Linking $link_to..."
+  console "Linking ${linkTo}..."
 
-  if [[ -f "$link_to" || -d "$link_to" || -f "$link_path" ]]; then
-    if [[ "$link_path" = "$link_from" ]]; then
+  if [[ -f "${linkTo}" || -d "${linkTo}" || -f "${linkPath}" ]]; then
+    if [[ "${linkPath}" = "${linkFrom}" ]]; then
       skip
       return
     fi
 
-    fail
-    die "File $link_to already exists." 71
+    fail "File ${linkTo} already exists."
   fi
 
-  if [[ ! -f "$link_path" ]]; then
-    rm "$link_to" >/dev/null 2>&1
-  fi
-
-  ln -s "$link_from" "$link_to" || {
-    fail
-    die "Failed to create link $link_from->$link_to" 72
+  ln -s "${linkFrom}" "${linkTo}" || {
+    fail "Failed to create link ${linkFrom}->${linkTo}"
   }
 
   pass
 }
 
 #-- Links ------------------------------------------------------------------------------------------
-link_home "shell/bash_aliases"   ".bash_aliases"
-link_home "shell/bash_exports"   ".bash_exports"
-link_home "shell/bash_functions" ".bash_functions"
-link_home "shell/bash_nocommit"  ".bash_nocommit"
-link_home "shell/bash_options"   ".bash_options"
-link_home "shell/bash_paths"     ".bash_paths"
-link_home "shell/bash_profile"   ".bash_profile"
-link_home "shell/bashrc"         ".bashrc"
-link_home "config/deadbeef"      ".config/deadbeef"
-link_home "config/mpv"           ".config/mpv"
-link_home "emacs.d"              ".emacs.d"
-link_home "git/gitconfig"        ".gitconfig"
-link_home "git/gitignore"        ".gitignore"
-link_home "config/npmrc"         ".npmrc"
+linkHome "shell/bash_aliases"   ".bash_aliases"
+linkHome "shell/bash_exports"   ".bash_exports"
+linkHome "shell/bash_functions" ".bash_functions"
+# linkHome "shell/bash_nocommit"  ".bash_nocommit"
+linkHome "shell/bash_options"   ".bash_options"
+linkHome "shell/bash_paths"     ".bash_paths"
+linkHome "shell/bash_profile"   ".bash_profile"
+linkHome "shell/bashrc"         ".bashrc"
+linkHome "config/deadbeef"      ".config/deadbeef"
+linkHome "config/mpv"           ".config/mpv"
+# linkHome "emacs.d"              ".emacs.d"
+linkHome "git/gitconfig"        ".gitconfig"
+linkHome "git/gitignore"        ".gitignore"
+# linkHome "config/npmrc"         ".npmrc"
 
-exit_header
+exitHeader
